# Generated by Django 2.2.2 on 2019-06-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='provice',
            new_name='province',
        ),
    ]
