# Generated by Django 2.2.2 on 2019-06-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileStatus',
        ),
    ]
