# Generated by Django 2.2.2 on 2019-07-03 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama_Jabatan')),
            ],
            options={
                'verbose_name_plural': 'jabatan',
                'db_table': 'pemerintahan_jabatan',
                'ordering': ['kelembagaan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Kelembagaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama Kelembagaan')),
            ],
            options={
                'verbose_name_plural': 'kelembagaan',
                'db_table': 'pemerintahan_kelembagaan',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pelatihan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama Pelatihan')),
            ],
            options={
                'verbose_name_plural': 'pelatihan',
                'db_table': 'pemerintahan_pelatihan',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pemerintahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama Lengkap')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goverment.Jabatan', verbose_name='nama kelembagaan')),
                ('kelembagaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goverment.Kelembagaan', verbose_name='nama kelembagaan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemerintahan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pemerintahan',
                'db_table': 'pemerintahan_jabatan_kelembagaan',
            },
        ),
        migrations.CreateModel(
            name='ProfilePemerintahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niap', models.CharField(max_length=50, verbose_name='Nomor Induk Aparatur Perangkat')),
                ('status_jabatan', models.CharField(choices=[('Struktural', 'Struktural'), ('Pelaksana', 'Pelaksana'), ('Definitif', 'Definitif'), ('Pejabat', 'Pejabat'), ('PLT', 'PLT'), ('YMT', 'YMT')], max_length=10)),
                ('no_sk', models.CharField(max_length=50, verbose_name='Nomer SK')),
                ('tgl_kep_pengangkatan', models.DateField(verbose_name='Tanggal Keputusan Pengangkatan')),
                ('tgl_pelantikan', models.DateField(verbose_name='Tanggal Pelatikan')),
                ('akhir_masa_jabatan', models.DateField(verbose_name='Akhir Masa Jabatan')),
                ('pekerjaan_asal', models.CharField(choices=[('Belum/Tidak Bekerja', 'Belum/Tidak Bekerja'), ('Mengurus Rumah Tangga', 'Mengurus Rumah Tangga'), ('Pelajar/Mahasiswa', 'Pelajar/Mahasiswa'), ('Pensiunan', 'Pensiunan'), ('Pegawai Negeri Sipil', 'Pegawai Negeri Sipil'), ('Tentara Nasional Indonesia', 'Tentara Nasional Indonesia'), ('Kepolisian RI', 'Kepolisian RI'), ('Perdagangan', 'Perdagangan'), ('Petani/Pekebun', 'Petani/Pekebun'), ('Peternak', 'Peternak'), ('Nelayan/Perikanan', 'Nelayan/Perikanan'), ('Industri', 'Industri'), ('Konstruksi', 'Konstruksi'), ('Transportasi', 'Transportasi'), ('Karyawan Swasta', 'Karyawan Swasta'), ('Karyawan BUMN', 'Karyawan BUMN'), ('Karyawan BUMD', 'Karyawan BUMD'), ('Karyawan Honorer', 'Karyawan Honorer'), ('Buruh Harian Lepas', 'Buruh Harian Lepas'), ('Buruh Tani/Perkebunan', 'Buruh Tani/Perkebunan'), ('Buruh Nelayan/Perikanan', 'Buruh Nelayan/Perikanan'), ('Buruh Peternakan', 'Buruh Peternakan'), ('Pembantu Rumah Tangga', 'Pembantu Rumah Tangga'), ('Tukang Cukur', 'Tukang Cukur'), ('Tukang Listrik', 'Tukang Listrik'), ('Tukang Batu', 'Tukang Batu'), ('Tukang Kayu', 'Tukang Kayu'), ('Tukang Sol Sepatu', 'Tukang Sol Sepatu'), ('Tukang Las/Pandai Besi', 'Tukang Las/Pandai Besi'), ('Tukang Jahit', 'Tukang Jahit'), ('Penata Rambut', 'Penata Rambut'), ('Penata Rias', 'Penata Rias'), ('Penata Busana', 'Penata Busana'), ('Mekanik', 'Mekanik'), ('Tukang Gigi', 'Tukang Gigi'), ('Seniman', 'Seniman'), ('Tabib', 'Tabib'), ('Paraji', 'Paraji'), ('Perancang Busana', 'Perancang Busana'), ('Penterjemah', 'Penterjemah'), ('Imam Masjid', 'Imam Masjid'), ('Pendeta', 'Pendeta'), ('Pastur', 'Pastur'), ('Wartawan', 'Wartawan'), ('Ustadz/Mubaligh', 'Ustadz/Mubaligh'), ('Juru Masak', 'Juru Masak'), ('Promotor Acara', 'Promotor Acara'), ('Anggota DPR-RI', 'Anggota DPR-RI'), ('Anggota DPD', 'Anggota DPD'), ('Anggota BPK', 'Anggota BPK'), ('Presiden', 'Presiden'), ('Wakil Presiden', 'Wakil Presiden'), ('Anggota Mahkamah', 'Anggota Mahkamah'), ('Anggota Kabinet/Kementerian', 'Anggota Kabinet/Kementerian'), ('Duta Besar', 'Duta Besar'), ('Gubernur', 'Gubernur'), ('Wakil Gubernur', 'Wakil Gubernur'), ('Bupati', 'Bupati'), ('Wakil Bupati', 'Wakil Bupati'), ('Walikota', 'Walikota'), ('Wakil Walikota', 'Wakil Walikota'), ('Anggota DPRD Propinsi', 'Anggota DPRD Propinsi'), ('Anggota DPRD Kabupaten/Kota', 'Anggota DPRD Kabupaten/Kota'), ('Dosen', 'Dosen'), ('Guru', 'Guru'), ('Pilot', 'Pilot'), ('Pengacara', 'Pengacara'), ('Notaris', 'Notaris'), ('Arsitek', 'Arsitek'), ('Akuntan', 'Akuntan'), ('Konsultan', 'Konsultan'), ('Dokter', 'Dokter'), ('Bidan', 'Bidan'), ('Perawat', 'Perawat'), ('Apoteker', 'Apoteker'), ('Psikiater/Psikolog', 'Psikiater/Psikolog'), ('Penyiar Televisi', 'Penyiar Televisi'), ('Penyiar Radio', 'Penyiar Radio'), ('Pelaut', 'Pelaut'), ('Peneliti', 'Peneliti'), ('Sopir', 'Sopir'), ('Pialang', 'Pialang'), ('Paranormal', 'Paranormal'), ('Pedagang', 'Pedagang'), ('Perangkat Desa', 'Perangkat Desa'), ('Kepala Desa', 'Kepala Desa'), ('Biarawati', 'Biarawati'), ('Wiraswasta', 'Wiraswasta'), ('Buruh Migran', 'Buruh Migran'), ('Lainnya', 'Lainnya')], max_length=100)),
                ('pangkat', models.CharField(choices=[('Tidak Ada', 'Tidak Ada'), ('Juru Muda', 'Juru Muda'), ('Juru Muda Tingkat I\t', 'Juru Muda Tingkat I\t'), ('Juru', 'Juru'), ('Juru Tingkat I', 'Juru Tingkat I'), ('Pengatur Muda', 'Pengatur Muda'), ('Pengatur Muda Tingkat I', 'Pengatur Muda Tingkat I'), ('Pengatur', 'Pengatur'), ('Pengatur Tingkat I', 'Pengatur Tingkat I'), ('Penata Muda', 'Penata Muda'), ('Penata Muda Tingkat I', 'Penata Muda Tingkat I'), ('Penata', 'Penata'), ('Penata Tingkat I', 'Penata Tingkat I'), ('Pembina', 'Pembina'), ('Pembina Tingkat I', 'Pembina Tingkat I'), ('Pembina Utama Muda', 'Pembina Utama Muda'), ('Pembina UtamaMadya', 'Pembina UtamaMadya'), ('Pembina Utama', 'Pembina Utama')], max_length=25)),
                ('golongan', models.CharField(choices=[('Tidak Ada', 'Tidak Ada'), ('I/a', 'I/a'), ('I/b', 'I/b'), ('I/c', 'I/c'), ('I/d', 'I/d'), ('II/a', 'II/a'), ('II/b', 'II/b'), ('II/c', 'II/c'), ('II/d', 'II/d'), ('III/a', 'III/a'), ('III/b', 'III/b'), ('III/c', 'III/c'), ('III/d', 'III/d'), ('IV/a', 'IV/a'), ('IV/b', 'IV/b'), ('IV/c', 'IV/c'), ('IV/d', 'IV/d')], max_length=5)),
                ('tmpt_lhr', models.CharField(max_length=50, verbose_name='Tempat Lahir')),
                ('tgl_lhr', models.DateField(verbose_name='Tanggal Lahir')),
                ('jk', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('agama', models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katholik', 'Katholik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Khong Hucu', 'Khong Hucu')], max_length=10)),
                ('pendidikan', models.CharField(choices=[('Tidak/Belum Sekolah', 'Tidak/Belum Sekolah'), ('Tidak Tamat SD/Sederajat', 'Tidak Tamat SD/Sederajat'), ('Tamat SD/Sederajat', 'Tamat SD/Sederajat'), ('SLTP/Sederajat', 'SLTP/Sederajat'), ('SLTA/Sederjat', 'SLTA/Sederjat'), ('Diploma I/II', 'Diploma I/II'), ('Akademi/Diploma III/S. Muda', 'Akademi/Diploma III/S. Muda'), ('DilpomaIV/Strata I', 'DilpomaIV/Strata I'), ('Strata II', 'Strata II'), ('Strata III', 'Strata III'), ('Pendidikan Non Formal', 'Pendidikan Non Formal')], max_length=50, verbose_name='Pendidikan Akhir')),
                ('siltap', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Penghasilan Tetap')),
                ('tunjangan', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Tunjangan Penghasilan')),
                ('sawah', models.PositiveIntegerField(verbose_name='Bengkok Sawah')),
                ('darat', models.PositiveIntegerField(verbose_name='Bengkok Darat')),
                ('alamat', models.CharField(max_length=150, verbose_name='Alamat Lengkap')),
                ('phone', models.CharField(max_length=14, verbose_name='Nomor Handphone')),
                ('status', models.CharField(choices=[('Belum Kawin', 'Belum Kawin'), ('Kawin', 'Kawin'), ('Cerai Hidup', 'Cerai Hidup'), ('Cerai Mati', 'Cerai Mati')], max_length=15)),
                ('suami_istri', models.CharField(max_length=50, verbose_name='Nama Istri/Suami')),
                ('tmpt_lhr_suami_istri', models.CharField(max_length=50, verbose_name='Tempat Lahir Istri/Suami')),
                ('tgl_lhr_suami_istri', models.DateField(verbose_name='Tanggal Lahir Istri/Suami')),
                ('agama_suami_istri', models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katholik', 'Katholik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Khong Hucu', 'Khong Hucu')], max_length=10, verbose_name='Agama Istri/Suami')),
                ('pendidikan_suami_istri', models.CharField(choices=[('Tidak/Belum Sekolah', 'Tidak/Belum Sekolah'), ('Tidak Tamat SD/Sederajat', 'Tidak Tamat SD/Sederajat'), ('Tamat SD/Sederajat', 'Tamat SD/Sederajat'), ('SLTP/Sederajat', 'SLTP/Sederajat'), ('SLTA/Sederjat', 'SLTA/Sederjat'), ('Diploma I/II', 'Diploma I/II'), ('Akademi/Diploma III/S. Muda', 'Akademi/Diploma III/S. Muda'), ('DilpomaIV/Strata I', 'DilpomaIV/Strata I'), ('Strata II', 'Strata II'), ('Strata III', 'Strata III'), ('Pendidikan Non Formal', 'Pendidikan Non Formal')], max_length=50, verbose_name='Pendidikan Akhir Istri/Suami')),
                ('anak_kandung', models.PositiveIntegerField(verbose_name='Total Anak Kandung')),
                ('anak_tiri', models.PositiveIntegerField(verbose_name='Total Anak Tiri')),
                ('anak_angkat', models.PositiveIntegerField(verbose_name='Total Anak Angkat')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goverment.Jabatan', verbose_name='Jabatan')),
                ('kelembagaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goverment.Kelembagaan', verbose_name='Jenis Kelembagaan')),
                ('pemerintahan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pemdes', to='goverment.Pemerintahan')),
            ],
            options={
                'verbose_name_plural': 'pemerintahan',
                'db_table': 'pemerintahan',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='jabatan',
            name='kelembagaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelambagaan', to='goverment.Kelembagaan'),
        ),
    ]
