# Generated by Django 2.2.2 on 2019-07-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goverment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jabatan',
            options={'ordering': ['kelembagaan__id'], 'verbose_name_plural': 'jabatan'},
        ),
    ]
