# Generated by Django 2.2.2 on 2019-07-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goverment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelembagaan',
            old_name='user',
            new_name='user_kelembagaan',
        ),
    ]
