# Generated by Django 2.2.2 on 2019-07-30 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goverment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pemerintahan',
            unique_together=set(),
        ),
    ]
