# Generated by Django 2.2.2 on 2019-07-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goverment', '0002_auto_20190730_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabatan',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nama_Jabatan'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='agama',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katholik', 'Katholik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Khong Hucu', 'Khong Hucu')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='agama_suami_istri',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katholik', 'Katholik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Khong Hucu', 'Khong Hucu')], max_length=10, null=True, verbose_name='Agama Istri/Suami'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='akhir_masa_jabatan',
            field=models.DateField(blank=True, null=True, verbose_name='Akhir Masa Jabatan'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='alamat',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Alamat Lengkap'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='anak_angkat',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Anak Angkat'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='anak_kandung',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Anak Kandung'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='anak_tiri',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Anak Tiri'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='darat',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bengkok Darat'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='golongan',
            field=models.CharField(blank=True, choices=[('Tidak Ada', 'Tidak Ada'), ('I/a', 'I/a'), ('I/b', 'I/b'), ('I/c', 'I/c'), ('I/d', 'I/d'), ('II/a', 'II/a'), ('II/b', 'II/b'), ('II/c', 'II/c'), ('II/d', 'II/d'), ('III/a', 'III/a'), ('III/b', 'III/b'), ('III/c', 'III/c'), ('III/d', 'III/d'), ('IV/a', 'IV/a'), ('IV/b', 'IV/b'), ('IV/c', 'IV/c'), ('IV/d', 'IV/d')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='jk',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True, verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='no_sk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomer SK'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='pangkat',
            field=models.CharField(blank=True, choices=[('Tidak Ada', 'Tidak Ada'), ('Juru Muda', 'Juru Muda'), ('Juru Muda Tingkat I\t', 'Juru Muda Tingkat I\t'), ('Juru', 'Juru'), ('Juru Tingkat I', 'Juru Tingkat I'), ('Pengatur Muda', 'Pengatur Muda'), ('Pengatur Muda Tingkat I', 'Pengatur Muda Tingkat I'), ('Pengatur', 'Pengatur'), ('Pengatur Tingkat I', 'Pengatur Tingkat I'), ('Penata Muda', 'Penata Muda'), ('Penata Muda Tingkat I', 'Penata Muda Tingkat I'), ('Penata', 'Penata'), ('Penata Tingkat I', 'Penata Tingkat I'), ('Pembina', 'Pembina'), ('Pembina Tingkat I', 'Pembina Tingkat I'), ('Pembina Utama Muda', 'Pembina Utama Muda'), ('Pembina UtamaMadya', 'Pembina UtamaMadya'), ('Pembina Utama', 'Pembina Utama')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='pekerjaan_asal',
            field=models.CharField(blank=True, choices=[('Belum/Tidak Bekerja', 'Belum/Tidak Bekerja'), ('Mengurus Rumah Tangga', 'Mengurus Rumah Tangga'), ('Pelajar/Mahasiswa', 'Pelajar/Mahasiswa'), ('Pensiunan', 'Pensiunan'), ('Pegawai Negeri Sipil', 'Pegawai Negeri Sipil'), ('Tentara Nasional Indonesia', 'Tentara Nasional Indonesia'), ('Kepolisian RI', 'Kepolisian RI'), ('Perdagangan', 'Perdagangan'), ('Petani/Pekebun', 'Petani/Pekebun'), ('Peternak', 'Peternak'), ('Nelayan/Perikanan', 'Nelayan/Perikanan'), ('Industri', 'Industri'), ('Konstruksi', 'Konstruksi'), ('Transportasi', 'Transportasi'), ('Karyawan Swasta', 'Karyawan Swasta'), ('Karyawan BUMN', 'Karyawan BUMN'), ('Karyawan BUMD', 'Karyawan BUMD'), ('Karyawan Honorer', 'Karyawan Honorer'), ('Buruh Harian Lepas', 'Buruh Harian Lepas'), ('Buruh Tani/Perkebunan', 'Buruh Tani/Perkebunan'), ('Buruh Nelayan/Perikanan', 'Buruh Nelayan/Perikanan'), ('Buruh Peternakan', 'Buruh Peternakan'), ('Pembantu Rumah Tangga', 'Pembantu Rumah Tangga'), ('Tukang Cukur', 'Tukang Cukur'), ('Tukang Listrik', 'Tukang Listrik'), ('Tukang Batu', 'Tukang Batu'), ('Tukang Kayu', 'Tukang Kayu'), ('Tukang Sol Sepatu', 'Tukang Sol Sepatu'), ('Tukang Las/Pandai Besi', 'Tukang Las/Pandai Besi'), ('Tukang Jahit', 'Tukang Jahit'), ('Penata Rambut', 'Penata Rambut'), ('Penata Rias', 'Penata Rias'), ('Penata Busana', 'Penata Busana'), ('Mekanik', 'Mekanik'), ('Tukang Gigi', 'Tukang Gigi'), ('Seniman', 'Seniman'), ('Tabib', 'Tabib'), ('Paraji', 'Paraji'), ('Perancang Busana', 'Perancang Busana'), ('Penterjemah', 'Penterjemah'), ('Imam Masjid', 'Imam Masjid'), ('Pendeta', 'Pendeta'), ('Pastur', 'Pastur'), ('Wartawan', 'Wartawan'), ('Ustadz/Mubaligh', 'Ustadz/Mubaligh'), ('Juru Masak', 'Juru Masak'), ('Promotor Acara', 'Promotor Acara'), ('Anggota DPR-RI', 'Anggota DPR-RI'), ('Anggota DPD', 'Anggota DPD'), ('Anggota BPK', 'Anggota BPK'), ('Presiden', 'Presiden'), ('Wakil Presiden', 'Wakil Presiden'), ('Anggota Mahkamah', 'Anggota Mahkamah'), ('Anggota Kabinet/Kementerian', 'Anggota Kabinet/Kementerian'), ('Duta Besar', 'Duta Besar'), ('Gubernur', 'Gubernur'), ('Wakil Gubernur', 'Wakil Gubernur'), ('Bupati', 'Bupati'), ('Wakil Bupati', 'Wakil Bupati'), ('Walikota', 'Walikota'), ('Wakil Walikota', 'Wakil Walikota'), ('Anggota DPRD Propinsi', 'Anggota DPRD Propinsi'), ('Anggota DPRD Kabupaten/Kota', 'Anggota DPRD Kabupaten/Kota'), ('Dosen', 'Dosen'), ('Guru', 'Guru'), ('Pilot', 'Pilot'), ('Pengacara', 'Pengacara'), ('Notaris', 'Notaris'), ('Arsitek', 'Arsitek'), ('Akuntan', 'Akuntan'), ('Konsultan', 'Konsultan'), ('Dokter', 'Dokter'), ('Bidan', 'Bidan'), ('Perawat', 'Perawat'), ('Apoteker', 'Apoteker'), ('Psikiater/Psikolog', 'Psikiater/Psikolog'), ('Penyiar Televisi', 'Penyiar Televisi'), ('Penyiar Radio', 'Penyiar Radio'), ('Pelaut', 'Pelaut'), ('Peneliti', 'Peneliti'), ('Sopir', 'Sopir'), ('Pialang', 'Pialang'), ('Paranormal', 'Paranormal'), ('Pedagang', 'Pedagang'), ('Perangkat Desa', 'Perangkat Desa'), ('Kepala Desa', 'Kepala Desa'), ('Biarawati', 'Biarawati'), ('Wiraswasta', 'Wiraswasta'), ('Buruh Migran', 'Buruh Migran'), ('Lainnya', 'Lainnya')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='pendidikan',
            field=models.CharField(blank=True, choices=[('Tidak/Belum Sekolah', 'Tidak/Belum Sekolah'), ('Tidak Tamat SD/Sederajat', 'Tidak Tamat SD/Sederajat'), ('Tamat SD/Sederajat', 'Tamat SD/Sederajat'), ('SLTP/Sederajat', 'SLTP/Sederajat'), ('SLTA/Sederjat', 'SLTA/Sederjat'), ('Diploma I/II', 'Diploma I/II'), ('Akademi/Diploma III/S. Muda', 'Akademi/Diploma III/S. Muda'), ('DilpomaIV/Strata I', 'DilpomaIV/Strata I'), ('Strata II', 'Strata II'), ('Strata III', 'Strata III'), ('Pendidikan Non Formal', 'Pendidikan Non Formal')], max_length=50, null=True, verbose_name='Pendidikan Akhir'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='pendidikan_suami_istri',
            field=models.CharField(blank=True, choices=[('Tidak/Belum Sekolah', 'Tidak/Belum Sekolah'), ('Tidak Tamat SD/Sederajat', 'Tidak Tamat SD/Sederajat'), ('Tamat SD/Sederajat', 'Tamat SD/Sederajat'), ('SLTP/Sederajat', 'SLTP/Sederajat'), ('SLTA/Sederjat', 'SLTA/Sederjat'), ('Diploma I/II', 'Diploma I/II'), ('Akademi/Diploma III/S. Muda', 'Akademi/Diploma III/S. Muda'), ('DilpomaIV/Strata I', 'DilpomaIV/Strata I'), ('Strata II', 'Strata II'), ('Strata III', 'Strata III'), ('Pendidikan Non Formal', 'Pendidikan Non Formal')], max_length=50, null=True, verbose_name='Pendidikan Akhir Istri/Suami'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Nomor Handphone'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='sawah',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bengkok Sawah'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='siltap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Penghasilan Tetap'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='status',
            field=models.CharField(blank=True, choices=[('Belum Kawin', 'Belum Kawin'), ('Kawin', 'Kawin'), ('Cerai Hidup', 'Cerai Hidup'), ('Cerai Mati', 'Cerai Mati')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='suami_istri',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nama Istri/Suami'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='tgl_kep_pengangkatan',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Keputusan Pengangkatan'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='tgl_lhr',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='tgl_lhr_suami_istri',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir Istri/Suami'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='tgl_pelantikan',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Pelatikan'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='tmpt_lhr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tempat Lahir'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='tmpt_lhr_suami_istri',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tempat Lahir Istri/Suami'),
        ),
        migrations.AlterField(
            model_name='profilepemerintahan',
            name='tunjangan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Tunjangan Penghasilan'),
        ),
    ]
