# Generated by Django 2.2.2 on 2019-07-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goverment', '0003_auto_20190701_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jabatan',
            options={'ordering': ['kelembagaan', 'id'], 'verbose_name_plural': 'jabatan'},
        ),
        migrations.AlterModelOptions(
            name='kelembagaan',
            options={'ordering': ['id'], 'verbose_name_plural': 'kelembagaan'},
        ),
    ]
