# Generated by Django 2.2.2 on 2019-07-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goverment', '0004_auto_20190701_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kelembagaanjabatan',
            options={'verbose_name_plural': 'Jabatan Kelembagaan'},
        ),
        migrations.AlterField(
            model_name='pemerintahan',
            name='golongan',
            field=models.CharField(choices=[('Tidak Ada', 'Tidak Ada'), ('I/a', 'I/a'), ('I/b', 'I/b'), ('I/c', 'I/c'), ('I/d', 'I/d'), ('II/a', 'II/a'), ('II/b', 'II/b'), ('II/c', 'II/c'), ('II/d', 'II/d'), ('III/a', 'III/a'), ('III/b', 'III/b'), ('III/c', 'III/c'), ('III/d', 'III/d'), ('IV/a', 'IV/a'), ('IV/b', 'IV/b'), ('IV/c', 'IV/c'), ('IV/d', 'IV/d')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pemerintahan',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='pemerintahan',
            name='niap',
            field=models.CharField(max_length=50, verbose_name='Nomor Induk Aparatur Perangkat'),
        ),
    ]
